# Generated by Django 3.2 on 2021-06-02 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='Default Name', max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('cert_level', models.CharField(blank=True, choices=[('OW', 'Open Water'), ('AOW', 'Advanced Open Water'), ('RD', 'Rescue Diver'), ('DEEP', 'Deep Diver'), ('TEC50', 'Technical 50m'), ('TRIMIX90', 'Trimix 90m'), ('DM', 'Divemaster'), ('INST', 'Instructor')], max_length=256, null=True)),
                ('equipment', models.CharField(blank=True, choices=[('FK', 'Full Kit'), ('TW', 'Tanks and Weights'), ('NO', 'No Equipment')], max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
