# Generated by Django 3.2 on 2021-05-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='default@email.com', max_length=255, null=True),
        ),
    ]
