# Generated by Django 3.2 on 2021-05-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cert_level',
            field=models.CharField(blank=True, choices=[('OW', 'Open Water'), ('AOW', 'Advanced Open Water'), ('RD', 'Rescue Diver'), ('DEEP', 'Deep Diver'), ('TEC50', 'Technical 50m'), ('TRIMIX90', 'Trimix 90m'), ('DM', 'Divemaster'), ('INST', 'Instructor')], default='OW', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='equipment',
            field=models.CharField(blank=True, choices=[('FK', 'Full Kit'), ('TW', 'Tanks and Weights'), ('NO', 'No Equipment')], default='FK', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='Default Name', max_length=256, null=True),
        ),
    ]
