# Generated by Django 3.2 on 2021-05-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210531_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='Default', max_length=256, null=True),
        ),
    ]
