# Generated by Django 3.2 on 2021-06-02 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('AM_BOAT', 'AM_BOAT'), ('PM_BOAT', 'PM_BOAT'), ('POOL', 'POOL'), ('SHORE', 'SHORE'), ('CLASS', 'CLASS')], max_length=255)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('dive_site_1', models.CharField(blank=True, max_length=255, null=True)),
                ('dive_site_2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team_members_off', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.day')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('initiated_date', models.DateField(auto_now_add=True)),
                ('diver_role', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_status', models.CharField(blank=True, choices=[('REQUESTED', 'REQUESTED'), ('COMPLETED', 'COMPLETED'), ('PENDING_CHANGE', 'PEDNING_CHANGE'), ('CANCELLED', 'CANCELLED')], max_length=255, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('activity_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.activitydetail')),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
                ('diver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activitydetail',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.day'),
        ),
        migrations.AddField(
            model_name='activitydetail',
            name='dive_guides',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
