# Generated by Django 3.0.6 on 2021-03-31 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team_members_off', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('trip_type', models.CharField(choices=[('AM_BOAT', 'AM_BOAT'), ('PM_BOAT', 'PM_BOAT'), ('POOL', 'POOL'), ('SHORE', 'SHORE'), ('CLASS', 'CLASS')], max_length=255)),
                ('dive_site_1', models.CharField(blank=True, choices=[('Arificial Reef', 'Arificial Reef'), ('Dibba Rock', 'Dibba Rock'), ('Cauliflower Reef', 'Cauliflower Reef'), ('The Nursery', 'The Nursery'), ('Inchcape 1', 'Inchcape 1'), ('Inchcape Deep', 'Inchcape Deep'), ('Snoopy Island', 'Snoopy Island'), ('Snoopy Deep', 'Snoopy Deep'), ('Deep Sand', 'Deep Sand'), ('Snoopy 50', 'Snoopy 50'), ('3 Rocks', '3 Rocks'), ('Car Cemetary', 'Car Cemetary'), ('Shark Island', 'Shark Island'), ('Coral Gardens', 'Coral Gardens'), ('Hole in the Wall', 'Hole in the Wall'), ('Inchcape 2', 'Inchcape 2'), ('Martini Rock', 'Martini Rock'), ('Other', 'Other')], max_length=255, null=True)),
                ('dive_site_2', models.CharField(blank=True, choices=[('Arificial Reef', 'Arificial Reef'), ('Dibba Rock', 'Dibba Rock'), ('Cauliflower Reef', 'Cauliflower Reef'), ('The Nursery', 'The Nursery'), ('Inchcape 1', 'Inchcape 1'), ('Inchcape Deep', 'Inchcape Deep'), ('Snoopy Island', 'Snoopy Island'), ('Snoopy Deep', 'Snoopy Deep'), ('Deep Sand', 'Deep Sand'), ('Snoopy 50', 'Snoopy 50'), ('3 Rocks', '3 Rocks'), ('Car Cemetary', 'Car Cemetary'), ('Shark Island', 'Shark Island'), ('Coral Gardens', 'Coral Gardens'), ('Hole in the Wall', 'Hole in the Wall'), ('Inchcape 2', 'Inchcape 2'), ('Martini Rock', 'Martini Rock'), ('Other', 'Other')], max_length=255, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Day')),
                ('dive_guides', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('initiated_date', models.DateField(auto_now_add=True)),
                ('activity', models.CharField(default='null', max_length=255)),
                ('equipment', models.CharField(default='null', max_length=255)),
                ('booking_status', models.CharField(blank=True, choices=[('REQUESTED', 'REQUESTED'), ('COMPLETED', 'COMPLETED'), ('PENDING_CHANGE', 'PEDNING_CHANGE'), ('CANCELLED', 'CANCELLED')], max_length=255, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
                ('diver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_instructor', to=settings.AUTH_USER_MODEL)),
                ('trip_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.TripDetail')),
            ],
        ),
    ]
